repositoryUrl: https://github.com/dynamsoft-docs/camera-enhancer-docs-js/blob/v2
repository: dynamsoft-docs/camera-enhancer-docs-js
docFullPath: https://www.dynamsoft.com/camera-enhancer/docs/v2/web/
firstLevelUrl: /camera-enhancer/docs/v2/web
docHomePage: /camera-enhancer/docs/v2/introduction/
needSearchIndex: true
searchNeedFilter: true

productUrl: https://www.dynamsoft.com/camera-enhancer/overview/
productName: Dynamsoft Camera Enhancer

introduction: /camera-enhancer/docs/v2/core/introduction/
parameters: /camera-enhancer/docs/v2/core/parameters/
license_activation: /camera-enhancer/docs/v2/core/license-activation/
release_notes: /camera-enhancer/docs/v2/core/release-notes/
parameter-reference: /camera-enhancer/docs/v2/core/parameters/reference/
faq: /camera-enhancer/docs/v2/core/faq/

js: /camera-enhancer/docs/v2/web/programming/javascript/
js-guide: /camera-enhancer/docs/v2/web/programming/javascript/user-guide/
js-api: /camera-enhancer/docs/v2/web/programming/javascript/api-reference/
js-rn: /camera-enhancer/docs/v2/web/programming/javascript/release-note/

reference: /camera-enhancer/docs/v2/parameters/reference/
enumerations: /camera-enhancer/docs/v2/parameters/enumerations/
mobile-enum: /camera-enhancer/docs/v2/programming/enumerations/

license-error: /camera-enhancer/docs/v2/core/faq/license-error/
contact-us: /camera-enhancer/docs/v2/core/faq/contact-us/
gallery: /camera-enhancer/docs/v2/core/resources/code-gallery/
all-release-note: /camera-enhancer/docs/v2/core/release-notes/
resource: /camera-enhancer/docs/v2/core/resources/

barcode-deploy-ios: /barcode-reader/programming/ios/api-reference/camera-enhancer/
barcode-deploy-android: /barcode-reader/programming/android/api-reference/camera-enhancer/
barcode-enum: /barcode-reader/parameters/enum/

assets: /camera-enhancer/docs/v2/web/assets/
edit_icon: /camera-enhancer/docs/v2/web/assets/img-icon/edit-icon.png
smile_icon: /camera-enhancer/docs/v2/web/assets/img-icon/icon-smile.png
sad_icon: /camera-enhancer/docs/v2/web/assets/img-icon/icon-sad.png
dbr_icon: /camera-enhancer/docs/v2/web/assets/img-icon/icon-dbr.svg
dwt_icon: /camera-enhancer/docs/v2/web/assets/img-icon/icon-dwt.svg
dnt_icon: /camera-enhancer/docs/v2/web/assets/img-icon/icon-dnt.svg

overview: /camera-enhancer/overview/
download: /camera-enhancer/downloads/

useVersionTree: false
isDCV: true
useJSVersionV3: true

baseurl: "/camera-enhancer/docs/v2/web/"
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-webp
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-seo-tag


edition: js

defaults:
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false
  - scope:
      path: "programming/javascript"
    values:
      docRootName: "Camera Enhancer JavaScript Edition" 
      docHomePage: "/camera-enhancer/docs/v2/web/programming/javascript/"

url: "https://www.dynamsoft.com" # sitemap root
